### ISSUE TITLE
State of Libre Graphics (LGM15)

### ISSUE THREAD

**Issue by xuv** [roelj/inklingreader#39]
Hello @roelj & @su-v 

LGM is starting end of this month and it has a "State of the Libre Graphics" talk as an intro to the conferences. I'm suggesting to submit InklingReader to that as it has achieved quite a lot of advancements since last year (new features and Inkscape plugin). 

Here's a post explaining what's required: http://libregraphicsmeeting.org/2015/state-of-libre-graphics/
I can fill that up if you want (or don't have time).

Tell me what you think.

**Comment by roelj** [comment]
That would be cool! If I understand correctly, it is a presentation about many projects, each project having one slide (and no speaker to explain it)?

I'm not good at graphical stuff, so I am probably not the right person to make a slide. So if you want to make something, that would be awesome.

Here's what I think has changed since last year (I might be forgetting important features though):
- An Inkscape extension (personally, I think this is the best addition!)
- Inkscape 0.91 support (implementing the viewBox attribute)
- More features of the WPI file format are supported (timing data)
- Better support for Mac OSX (it compiles without Mac OSX-specific code)
- JSON and CSV output for "easy" data analysis
- A proof-of-concept implementation of the "online-mode" for GNU/Linux.

Not exactly a feature, but nevertheless important:
- InklingReader is now an official GNU package (thus GNU InklingReader). This move is another statement towards keeping the code Free Software and makes it easier for distributions to include GNU InklingReader in their distribution.

The future:
- I received an e-mail about creating "mouse emulation" for Mac OSX. This would simply make "online-mode" for Mac OSX work as well. The person wants to put some effort into writing it himself as well. So I hope we will see some results from this.
- Technical changes are pending. I have an almost-complete rewrite of the SVG output, allowing for a show/hide per layer feature.
- I have seen screenshots of InklingReader on KDE and Unity. I realize I have made it look really bad on anything other than GNOME. So changes to the GUI to make it look better on anything other than GNOME are on my to-do list.
- Currently, I'm putting my spare time into adding Inkling support to the Wacom Linux driver, which would make the online-mode work with the optimizations from the kernel driver. This will probably fix the problems with the current proof-of-concept implementation. It also removes the requirement to run InklingReader to get "online-mode" working.

Maybe we could add some requests for people viewing the slide:
- Support for more digital pens. For this we would need data from other pens, so it can be analyzed and the format can read by InklingReader. So if anyone has a digital pen that doesn't play nice with GNU/Linux, this project provides a lot to get decent support. All we should have to do is figure out the data format, and write a parser for it. I can do this if needed.

Now I realize this is quite a large list of things. So feel free to pick some things out of it, or not use it at all ;).

Thank you for being part of this project, and keeping interest in it.

**Comment by xuv** [comment]
Wow. This is a great list. I didn't expect all that news. It's nice to see all this activity going on around this project. I'm really happy to know you still work on the Wacom driver. This is great.

I'll craft some slides. And post them here for your approval.

There will be a speaker. Will have to send notes in relation to each slides so s/he can comment on them.

Will keep you posted.

**Comment by roelj** [comment]
Great. Thanks a lot! I am looking forward to it. If there's anything I can help with, please let me know.

Kernel development is completely new to me, so it takes some time to get right. But I am making progress on it.

Maybe @su-v has some ideas for the slides as well?

**Comment by xuv** [comment]
Here are the slides. I still have to write the text that will be read over it, but it will mainly be a copy paste of what you wrote in your first post of this thread. 

I'm trying to actually redraw those slides using the Inkling (that would be a cool effect) but need to improve my wirting a little for this. Will see if that comes out good or not and will let you know. 

This is mainly here to see if you agree with the content and organization of it.

![inklingreader-0](https://cloud.githubusercontent.com/assets/192539/7241883/694ab04c-e78b-11e4-9000-07d5d9e98374.png)

![inklingreader-1](https://cloud.githubusercontent.com/assets/192539/7241886/6fcf6fac-e78b-11e4-8631-4224a470effa.png)

![inklingreader-2](https://cloud.githubusercontent.com/assets/192539/7241896/77c6caca-e78b-11e4-9c46-eb6cd1a91669.png)

**Comment by roelj** [comment]
That looks mostly fine to me. Just a few notes:
- As a GNU package, it should carry the GNU name: GNU InklingReader.
- It has been a group effort to get all features. For example, the Inkscape extension is written and maintained by @su-v . And because of your (@xuv) publicity the project gets more feedback, which I really appreciate. So maybe the "by Roel Janssen" should be extended to "by Roel Janssen, <su-v's name here (really sorry I don't know)> and Julien Deswaef". If both of you agree to it.

Thanks for your work. I am looking forward to the redraw too!

**Comment by xuv** [comment]
Hey @roelj 
Thanks for your comments. Really appreciate your proposal of getting my name next to yours. But I sincerely feel you've done all the hard work. You've initiated the project, you've done most of the coding, so it feels normal for me to put your name upfront on this. But I've reworked the first slide to integrate your remarks. Tell me if that sounds fine with you and @su-v of course.

![inklingreader-0](https://cloud.githubusercontent.com/assets/192539/7258908/87fe484e-e82d-11e4-80c6-1368d905fd49.png)

**Comment by roelj** [comment]
That's fine with me. Let's wait for @su-v.
If I can help you with anything, just let me know.

**Comment by xuv** [comment]
Well, here's what it looks like when "drawn" and imported with inklingreader. It's not perfect but I think it does the job. Tell me zhat you think.

![inklingreader-0](https://cloud.githubusercontent.com/assets/192539/7264555/ae57899c-e85a-11e4-8105-1e01e78361b8.png)
![inklingreader-1](https://cloud.githubusercontent.com/assets/192539/7264556/ae579e0a-e85a-11e4-8336-c394e349c629.png)
![inklingreader-2](https://cloud.githubusercontent.com/assets/192539/7264554/ae57220e-e85a-11e4-9dd5-5c1ef84effa4.png)

**Comment by roelj** [comment]
I think the drawing style is cool. Maybe using different colors would be helpful for people reading it. Possibly toggle between two colors per line (bullet point).

I created a colored version of the title slide:
![Title slide - colored](http://roelj.com/InklingReader-slide1.png)

Multiple colors or one color is both fine with me. What do you think?

Thanks a lot already!

**Comment by su-v** [comment]
Sorry for being late to comment - slides look great to me (when used in a presentation, I imagine that the colored version will be easier to read), and the text covers it all :-)

**Comment by xuv** [comment]
Cool. Changes done. Glad everyone likes it and is on the same page. :)
Sending it now.

![inklingreader-0](https://cloud.githubusercontent.com/assets/192539/7276159/f2f55464-e8d5-11e4-8da8-d3223e54cdd4.png)
![inklingreader-1](https://cloud.githubusercontent.com/assets/192539/7276160/f2f616ec-e8d5-11e4-9d92-1a134dfc335e.png)
![inklingreader-2](https://cloud.githubusercontent.com/assets/192539/7276161/f2f7138a-e8d5-11e4-8c01-d2f76452785f.png)
