### ISSUE TITLE
calibration pressure

### ISSUE THREAD

**Issue by b4zz4** [roelj/inklingreader#44]
It is possible to calibrate the level that pressure in the on-line mode?

**Comment by roelj** [comment]
No. It's up to the driver to do that. Currently, online-mode uses a virtual mouse driver, which is limited in this aspect.

Ideally, we want to add support for Inkling's online-mode to the Wacom driver in Linux. Unfortunately that is not my list of things I could do, because I don't know how to do it, and I don't have enough free time to learn it.

You could experiment with the online-mode code since it is fairly simple.
