### ISSUE TITLE
Trouble with librsvg when using ./configure or autoreconf -i

### ISSUE THREAD

**Issue by mondata** [roelj/inklingreader#52]
I should preface this with the fact that I am new to compiling software. I have read everything in this github and made many queries to google.

I am using Ubuntu Studio 16.04LTS which when queried tells me I have the latest version of librsvg. It appears to be stored in the directory /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders. The file is libpixbufloader-svg.so. I have tried to download a new librsvg but the OS repeats that I have the most recent version. Am I right with this?

./configure and autoreconf -i now want me to do something with either PKG_CONFIG_PATH environment variable if software installed in a non-standard prefix or set environment variables rsvg_CFLAGS and rsvg_LIBS to avoid calling pkg-config.

Now I am totally lost. Can you please help. Thanks.

**Comment by roelj** [comment]
To compile programs written in C you not only need the shared library (`*.so` file), but also the header files (`*.h`) and, in this case, a `pkg-config` file that specifies which command-line arguments to pass to the compiler.

So, the easiest way is to install the `librsvg2-dev` package (note: the `-dev` part is important).  The `./configure` step runs `pkg-config` to find `librsvg2` on your system.  Only having the shared library file on your system is not enough; you also need the `pkg-config` file so that `./configure` can find it.

**Comment by roelj** [comment]
Hi @mondata!  Did you get it to work?

**Comment by roelj** [comment]
Thanks!  That's an interesting use-case (using it with FreeCAD).  If I may ask, do you use the "live" mode to sketch, or do you convert it to SVG (or another format), and import it into FreeCAD?  (Forgive my lack of knowledge about FreeCAD.)

The reason I ask is that it's quite trivial to add output formats to InklingReader to accomodate for import into other programs.

**Comment by roelj** [comment]
The original issue was resolved, so I am closing this issue.  Thanks!
